% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 27-Jan-2012 10:54:55
%  MATLAB version: 7.13.0.564 (R2011b)
% -------------------------------------------------------------------
Busses;

systemStatus = Simulink.Signal;
systemStatus.RTWInfo.StorageClass = 'ExportedGlobal';
systemStatus.RTWInfo.Alias = '';
systemStatus.RTWInfo.Alignment = -1;
systemStatus.RTWInfo.CustomStorageClass = 'Default';
systemStatus.Description = 'Stores the status of the vehicle';
systemStatus.DataType = 'Bus: SystemStatus';
systemStatus.Min = [];
systemStatus.Max = [];
systemStatus.DocUnits = '';
systemStatus.Dimensions = 1;
systemStatus.DimensionsMode = 'Fixed';
systemStatus.Complexity = 'real';
systemStatus.SampleTime = -1;
systemStatus.SamplingMode = 'Sample based';
systemStatus.InitialValue = '';
assignin('base', 'systemStatus', systemStatus);
