function dynamic_plots(datafile, auto_run, saveVideo)
% Show an animated graph of the vehicle during an autonomous run
%   Usage: dynamic_plots(data, RUN_NUMBER, SAVE_TO_VIDEO)
%   data (struct) - A struct generated by ProcessCsvData()
%   auto_run (int) - The autonomous run number. Look this up by running
%   `static_plots` on your data and looking at the title of the plots.
%   saveVideo (bool) - Whether to save this as a video file. Useful for
%   sending to others.

    % Acquire data from run
    data = ProcessCsvFile(datafile);
    
    % Check that all timestamps are unique, otherwise things explode later
    assert(length(data.timestamp) == length(unique(data.timestamp)), 'Timestamp data must be unique for calculations');
    
    % And let's start our timestamps at 0, which makes the plots a little
    % nicer.
    data.timestamp = data.timestamp - data.timestamp(1);

    % Generate a filename for the video file if one is desired
    if saveVideo
        [~, videoFileName, ~] = fileparts(datafile);
        videoFileName = sprintf('%s-run-%d.avi', videoFileName, auto_run);
    else
        videoFileName = '';
    end
        
    if isfield(data, 'CONTROLLER_DATA')
        dynamic_plots_cdata(data, auto_run, videoFileName);
    else
        dynamic_plots_gcs(data, auto_run, videoFileName);
    end
end