% Plot the different rudder commands
figure;
hold on;
title('Rudder commands');

rads_to_deg = 180 / pi;

% Plot the actual commanded rudder
% `valid_range` already appears in the workspace (generated by
% Replay_sim_init.m)
rudder_cmd_actual = data.BASIC_STATE.commanded_auto_rudder_angle(valid_range);
rudder_cmd_actual_indices = ~isnan(rudder_cmd_actual);
rudder_cmd_actual = rudder_cmd_actual(rudder_cmd_actual_indices);
rudder_time = data.timestamp(valid_range);
rudder_time = rudder_time(rudder_cmd_actual_indices);
rudder_time = rudder_time - rudder_time(1);
plot(rudder_time, rads_to_deg * rudder_cmd_actual, 'b.-');

% Plot the actual rudder angle
rudder_actual = data.BASIC_STATE.rudder_angle(valid_range);
rudder_actual_indices = ~isnan(rudder_actual);
rudder_actual = rudder_actual(rudder_actual_indices);
plot(rudder_time, rads_to_deg * rudder_actual, 'r--');

% Plot the simulated commanded angle
sim_commanded_angle = squeeze(command_r);
plot(tout, rads_to_deg*sim_commanded_angle, 'k.-');

ylabel('Rudder angle (deg');
xlabel('Time (s)');
legend({'Actual commmanded', 'Actual angle', 'Sim commanded'});