% These constants are specific to the simulator and are not necessary for
% the compilation of code_gen.mdl

% Initial latitude & longitude. This provides the baseline for the plant
% to generate GPS data.
initial_LL = [36.9543845; -122.0018435];
phi_0 = 0;              % Initial heading (radians, eastward positive from north)
v_0 = 0;                % Initial speed (m/s)
battery_tray_angle = 0; % Initial battery tray angle

% External forces
%water_current = [sqrt(2)/2 sqrt(2)/2]; % m/s in North,East coordinates
water_current = [0 0];

% Physical input/output parameters
% OC2max is used by the output compare for mapping into/out of sample units
% and real-world seconds. This value is generated by Lubin's Blockset so
% when used in simulation it must be generated.
OC2max = 49999; % Parameter used for calculating up-time & period for output compare 2.
