#include "Parameters.h"
#include "Node.h"
#include "PrimaryNode.h"
#include "MavlinkGlue.h"

// This file is the main header file generated by Simulink/MATLAB. Name matches the model used to 
// generate the code.
#include "controller.h"

#include <stdint.h>
#include <stddef.h>

static const Parameter params[] = {
    {"ModeAuto", NULL, (void(*)())SetAutoMode, (void(*)())GetAutoMode, PARAMETERS_DATATYPE_UINT8},
    {"Wheelbase", &wheelbase, NULL, NULL, PARAMETERS_DATATYPE_REAL32},
    {"Gps_SlewLimit", &gps_leap_rate_limit, NULL, NULL, PARAMETERS_DATATYPE_INT32},
    {"Gps_OriginLat", &gpsOrigin[0], NULL, NULL, PARAMETERS_DATATYPE_INT32},
    {"Gps_OriginLon", &gpsOrigin[1], NULL, NULL, PARAMETERS_DATATYPE_INT32},
    {"Gps_OriginAlt", &gpsOrigin[2], NULL, NULL, PARAMETERS_DATATYPE_INT32},
    {"L2+_T*", &tStar, NULL, NULL, PARAMETERS_DATATYPE_REAL32},
    {"L2+_MaxDownPath*", &maxDwnPthStar, NULL, NULL, PARAMETERS_DATATYPE_REAL32},
    {"L2+_TanInter", &tanIntercept, NULL, NULL, PARAMETERS_DATATYPE_REAL32},
    {"L2+_SwitchDist", &switchDistance, NULL, NULL, PARAMETERS_DATATYPE_REAL32},
    {"L2+_KPsiDot", &KPsiDot, NULL, NULL, PARAMETERS_DATATYPE_REAL32},
    {"L2+_OffsetFix", &GpsOffsetCorrectionEnable, NULL, NULL, PARAMETERS_DATATYPE_UINT8}
};

// Expose both the list of parameters and the total to the Parameters library.
const Parameter *onboardParameters = params;
const uint16_t PARAMETERS_TOTAL = sizeof(params)/sizeof(Parameter);